<?php
/**
 * Aligent CartCheckItOut
 *
 * @category   Aligent
 * @package    aligent-cartcheckitout
 * @copyright  Copyright (c) 2017 Aligent
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Chris Dorward <chris.dorward@aligent.com.au>
 *
 * /app/design/frontend/base/default/template/aligent/cartcheckitout/checkout/screens/password.phtml
 *
 */
?>
<div class="password">
    <h1 class="checkout-title" id="password-title"></h1>
    <div class="password-form">
        <div class="screen-desc" id="password-instructions"></div>
        <div id="password-input">
            <div class="form-label" id="password-feedback">
                <?php echo $this->__('Password'); ?>
            </div>

            <input
                id="input-password"
                type="password"
                autocomplete="password"
            />
            <input
                id="btn-password-continue"
                type="button"
                value="<?php echo $this->__('CONTINUE'); ?>"
            />
        </div>
        <div id="password-forgotten-loading" style="display:none;">
            <div class="password-forgotten-loading">
                <img
                        alt="Checking account..."
                        src="<?php echo $this->getSkinUrl('images/aligent/cartcheckitout/ajax-loader_blue.gif'); ?>" />
                <p><span id="password_loading_message"><?php echo $this->__('Checking account...'); ?></span></p>
            </div>
        </div>
        <div id="password-forgotten" style="display:none;">
            <span id="password-forgotten-text">Email has been sent</span>
            <input
                    id="btn-password-retry"
                    type="button"
                    value="<?php echo $this->__('Enter password again'); ?>"
            />
        </div>

        <div class="checkout-as-guest">
            <span class="forgotten-password"><a href="#" id="forgotten-password"><?php echo $this->__('Forgotten your password?'); ?></a></span>
            <span class="guest-checkout"><a href="#" id="checkout-as-guest"><?php echo $this->__('Checkout as guest'); ?></a></span>
        </div>
        <?php if($this->hasSocialSignin()): ?>
            <div class="social-connect">
                <div class="social-instructions"><?php echo $this->__('or sign in with...'); ?></div>
                <?php echo $this->getChildHtml('checkout.social')?>
            </div>
        <?php endif; ?>
    </div>
    <div class="password-loading">
        <img
            alt="checking password..."
            src="<?php echo $this->getSkinUrl('images/aligent/cartcheckitout/ajax-loader_blue.gif'); ?>" />
        <p><span id="password_loading_message"></span></p>
    </div>
</div>
