<?php
/**
 * Aligent CartCheckItOut
 *
 * @category   Aligent
 * @package    aligent-cartcheckitout
 * @copyright  Copyright (c) 2017 Aligent
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Chris Dorward <chris.dorward@aligent.com.au>
 *
 * /app/design/frontend/base/default/template/aligent/cartcheckitout/_partials/select-country.phtml
 *
 */
?>
<?php

    $defaultCountry = $this->getSelectedCountry();
    foreach ($this->getCountryList() as $country) {
        if ($country['label'] != '1'){
            $selected = '';
            if ($country['value'] == $defaultCountry){
                $selected = 'selected="selected"';
            }
            $maxLabelLength = 30;
            if(strlen($country['label']) > $maxLabelLength){
                $country['label'] = substr($country['label'],0,$maxLabelLength) . "...";
            }

            echo '<option ' . $selected . 'value="' . $country['value'] . '">' . $country['label']. '</option>';
        }
    }
?>
