<?php
/**
 * Aligent CartCheckItOut
 *
 * @category   Aligent
 * @package    aligent-cartcheckitout
 * @copyright  Copyright (c) 2017 Aligent
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Chris Dorward <chris.dorward@aligent.com.au>
 *
 * /app/design/frontend/base/default/template/aligent/cartcheckitout/_partials/empty-cart.phtml
 *
 */
?>
<div class="empty-cart">
    <p><?php echo $this->__('You have no items in your shopping cart.'); ?></p>
    <p>Click <a href="/" title="continue shopping"><?php echo $this->__('here'); ?></a> <?php echo $this->__('to continue shopping.'); ?></p>
</div>
