<?php
/**
 * Aligent CartCheckItOut
 *
 * @category   Aligent
 * @package    aligent-cartcheckitout
 * @copyright  Copyright (c) 2017 Aligent
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Chris Dorward <chris.dorward@aligent.com.au>
 *
 * /app/design/frontend/base/default/template/aligent/cartcheckitout/_partials/newsletter.phtml
 *
 */
?>
<div class="newsletter">
    <input
        type="checkbox"
        class="checkbox"
        id="newsletter-checkbox"
        checked="checked"
    />
    <label for="newsletter-checkbox"><?php echo $this->__('Sign up to Summer Lovers Club to be in the know!<br /><small>*By subscribing you agree to our <a target="_blank" href="/faq/privacy">privacy policy</a> terms and conditions.'); ?></small></label>
</div>